version: '3.8'
services:
  redis:
    image: redis:alpine
    ports:
      - 6379:6379
    networks:
      - redis
  customer:
    build:
      context: .
      args:
        - GO_MAIN=src/customer/main.go
      dockerfile: Dockerfile
    environment:
      - REDIS=redis:6379
      - CUSTOMER_WAIT=5000
    depends_on:
      - redis
    networks:
      - redis
  barista:
    build:
      context: .
      args:
        - GO_MAIN=src/barista/main.go
      dockerfile: Dockerfile
    environment:
      - REDIS_HOST=redis:6379
    depends_on:
      - redis
    networks:
      - redis
  machine:
    build:
      context: .
      args:
        - GO_MAIN=src/machine/main.go
      dockerfile: Dockerfile
    environment:
      - REDIS_HOST=redis:6379
      - BREW_DURATION=1000
    depends_on:
      - redis
    networks:
      - redis

networks:
  redis: