---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: spawn
automountServiceAccountToken: false
imagePullSecrets:
- name: ghcr
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: job-spawn
rules:
- apiGroups: ["batch"] # "" indicates the core API group
  resources: ["jobs"]
  verbs: ["get", "watch", "list", "create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: job-spawn
subjects:
- kind: ServiceAccount
  name: spawn
roleRef:
  kind: Role
  name: job-spawn
  apiGroup: rbac.authorization.k8s.io
...
